# Step 1: build-stage
FROM node:16.15-slim as build-stage

WORKDIR /usr/src/app
COPY package.json ./
COPY ./yarn.lock ./ 
RUN yarn install 
COPY . .

ARG BASE_URL
ENV REACT_APP_API_URL=${BASE_URL}

RUN yarn build

#Step 2: Copy into server
FROM caddy:2.5.1-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile
COPY --from=build-stage /usr/src/app/build /srv

EXPOSE 80
EXPOSE 443