version: "3.8"

services:
  client:
    depends_on:
      - api
    image: allamasln/tbs-client-prod:${ENV_VERSION}
    stdin_open: true
    ports:
      - 80:80
      - 443:443
    networks:
      - mern-app
    restart: unless-stopped
    volumes:
      - caddy-data:/data
      - caddy-config:/config

  api:
    image: allamasln/tbs-api:${ENV_VERSION}
    ports:
      - 3001:3001
    networks:
      - mern-app
    restart: unless-stopped

networks:
  mern-app:
    driver: bridge

volumes:
  tbs-mongo:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
