version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: tbstore_client:1
    container_name: tbs_client
    ports:
      - 80:80
    restart: unless-stopped

  api:
    depends_on:
      - db
    build: ./api
    image: tbstore_api:1
    container_name: tbs_api
    ports:
      - 3001:3001
    environment:
      CORSHEADER: "http://localhost:3000"
      DB_URL: mongodb://db/tbstore
    command: ./docker-entrypoint.sh
    restart: unless-stopped
  db:
    image: mongo:5.0.7-focal
    container_name: tbs_db
    ports:
      - 27017:27017
    volumes:
      - tbstore:/data/db
    restart: unless-stopped
volumes:
  tbstore:
