name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push api server image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:api"
          push: true
          tags: allamasln/tbs-api:1
      - name: Build and push client-dev
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:client"
          push: true
          tags: allamasln/tbs-client-dev:1
      - name: Build and push client-prod
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:client"
          path: "{{context}}/Dockerfile.prod"
          push: true
          tags: allamasln/tbs-client-prod:1
